// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/17/2025, 3:23:36 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/FrontendDevelopment/PortFolio Platform/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/FrontendDevelopment/PortFolio Platform/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/FrontendDevelopment/PortFolio Platform/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/FrontendDevelopment/PortFolio Platform/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/FrontendDevelopment/PortFolio Platform/plugins/**/*.{js,ts,mjs}","D:/FrontendDevelopment/PortFolio Platform/composables/**/*.{js,ts,mjs}","D:/FrontendDevelopment/PortFolio Platform/utils/**/*.{js,ts,mjs}","D:/FrontendDevelopment/PortFolio Platform/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/FrontendDevelopment/PortFolio Platform/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/FrontendDevelopment/PortFolio Platform/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/FrontendDevelopment/PortFolio Platform/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;