// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/18/2025, 8:59:06 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/Portfolio-me/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Portfolio-me/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Portfolio-me/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Portfolio-me/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Portfolio-me/plugins/**/*.{js,ts,mjs}","D:/Portfolio-me/composables/**/*.{js,ts,mjs}","D:/Portfolio-me/utils/**/*.{js,ts,mjs}","D:/Portfolio-me/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Portfolio-me/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Portfolio-me/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Portfolio-me/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;